config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'admin' => 'admin#index' 

  controller :sessions do
    get 'login' => :new 
    post 'login' => :create 
    delete 'logout' => :destroy
  end

  get "sessions/create" 

  get "users/forgot_password", to: "users#forgot_password", :as => :user_forgot_password
  
  post "users/forgot_password", to: "users#handle_forgot_password"

  get "users/reset_password", to: "users#reset_password"
  
  post "users/reset_password", to: "users#handle_reset_password"


  delete "sessions/destroy" 

  resources :users 

  get '/users/:token/unlock', to: 'users#unlock', :as => :unlock_user
  
  root to: "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates  :email,     :presence   => true,
            :format                 => { with: VALID_EMAIL_REGEX },
            :uniqueness             => {:case_sensitive => false}

  validates  :password,  :presence   => true,
            :confirmation           => true,
            :length                 => {:within => 6..40}, :on => :create

  # Determine admin role for user
  # enum role: [:user, :vip, :admin]

  # after_initialize :set_default_role, :if => :new_record?

  # def set_default_role
  #   self.role ||= :user
  # end

  has_secure_password

  has_secure_token :reset_token

  #send email for user after registration
  after_create :send_welcome_email
  def send_welcome_email
    UserMailer.welcome_email(self).deliver
  end
  
  after_destroy :ensure_an_admin_remains
  private
  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end 
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController 
  def index
    @total_users = User.count
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
  before_action :authorize
  def user_signed_in?
    session[:user_id].present?
  end

  def current_user
    user = User.find_by(id: session[:user_id]) 
  end
  helper_method :current_user
  helper_method :user_signed_in?

  protected
  def authorize
    unless User.find_by(id: session[:user_id])
      redirect_to login_url, notice: "Please log in" 
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize, only: [:new, :create]
  before_action :not_sign_in, only: [:new]
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user.present?
      if  user.sign_in_count >=3  
        UserMailer.lock_account_email(user).deliver
        redirect_to login_url, alert: "User has login more than 3 times" 
      else
        if user.authenticate(params[:password])
          user.sign_in_count = 0
          user.save
          session[:user_id] = user.id
          redirect_to admin_url
        else
          user.sign_in_count += 1 
          user.save
          redirect_to login_url, alert: "Invalid user/password combination" 
        end
      end
    else
      redirect_to login_url, alert: "Invalid user/password combination" 
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end

  def not_sign_in
    if current_user.present?
      redirect_to user_path(current_user)
    end
  end

  # def forgotten_password
  #   user = User.find_by(email: params[:email])
  #       debugger
  #   # UserMailer.forgotten_password_email.deliver
  # end

  # def reset_password
  #   # UserMailer.forgotten_password_email.deliver 

  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :admin_only, only: [:index]
  skip_before_action :authorize, only: [:forgot_password, :reset_password, :handle_forgot_password, :handle_reset_password ]
  include UsersHelper
  # GET /users
  # GET /users.json
  def index
    @users = User.order(:email)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User #{@user.email} was successfully created." }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: "User #{@user.email} was successfully created." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    begin
      @user.destroy
      flash[:notice] = "User #{@user.email} deleted" 
    rescue StandardError => e
      flash[:notice] = e.message
    end
    respond_to do |format|
      format.html { redirect_to users_url } 
      format.json { head :no_content }
    end
  end

  def unlock
    @user = User.find_by(reset_token: params[:token])
    @user.sign_in_count = 0
    @user.save
    redirect_to login_path
  end

  def admin_only
    unless admin?
      redirect_to welcome_index_path, :alert => "Access denied."
    end
  end

  def forgot_password
    # user = User.find_by(email: params[:email])
    # UserMailer.forgot_password_email.deliver

  end

  def handle_forgot_password
    @email = params[:email]
    UserMailer.forgot_password_email(@email).deliver 
  end

  def reset_password

  end

  def handle_reset_password
    user = User.find_by(email: params[:email])
    if params[:password_confirmation] === params[:password]
      user.password = params[:password]
      user.password_confirmation = params[:password_confirmation]
      user.save
      redirect_to login_path, :alert => "Reset Password succesful"
    else
      redirect_to reset_password_path, :alert => "Password must matched"
    end
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])

  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
end

app/helpers/users_helper.rb
module UsersHelper
  def admin?
    current_user.role == "admin"
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1> It's <%= Time.now %>
We have <%= pluralize(@total_orders, "order") %>.
The index() action sets up the count.

app/views/layouts/_authenticate.html.erb
  <% if user_signed_in? %>
    <li><%= link_to "Log out", sessions_destroy_path, method: :delete %></li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to "Edit your profile", edit_user_path(current_user)%></li>
      </ul>
    </li>
    
    <% else %>
    <li><%= link_to "Log in", login_path %></li>
    <li><%= link_to "Sign up", new_user_path %></li>
  <%end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-default bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>

  <div class="collapse navbar-collapse pull-right" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Log out", sessions_destroy_path, method: :delete, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Your Profile
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "nav-link" %>
            <%= link_to "View your profile", user_path(current_user), class: "nav-link" %>
          </div>
        </li>
      <%else %>
        <li><%= link_to "Log in", login_path, class: "nav-link" %></li>
        <li><%= link_to "Sign up", new_user_path, class: "nav-link" %></li>
      <% end %>
      
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LoginWithoutDevise</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <% if user_signed_in? %>
    <li><%= link_to "Log out", sessions_destroy_path, method: :delete %></li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to "Edit your profile", edit_user_path(current_user)%></li>
      </ul>
    </li>
    
    <% else %>
    <li><%= link_to "Log in", login_path %></li>
    <li><%= link_to "Sign up", new_user_path %></li>
  <%end %>
  <%= yield %>
    <div class="container ">
        <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/users/_form.html.erb
<div class="depot_form">
  <%= form_for @user do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <fieldset>
      <legend>Enter User Details</legend>

      <div class="field">
        <%= f.label :name, 'Email:'%>
        <%= f.text_field :email, size: 40 %>
      </div>

      <div class="field">
        <%= f.label :password, 'Password:' %>
        <%= f.password_field :password, size: 40 %>
      </div>

      <div class="field">
        <%= f.label :password_confirmation, 'Confirm:' %>
        <%= f.password_field :password_confirmation, size: 40 %>
      </div>

      <div class="actions"> 
        <%= f.submit %>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/forgot_password.html.erb
<h2> Please input your email</h2>
<%= form_tag do %>
  <div>
    <%= label_tag :email, 'Email:' %>
    <%= text_field_tag :email, params[:email] %>
  </div>

  <div>
    <%= submit_tag "Sumit" %> 
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<% if notice %>
  <p id="notice"><%= notice %></p> 
<% end %>
<table>
  <thead>
   <tr>
     <th>No.</th>
     <th>Email</th>
     <th>Role</th>
   </tr>
  </thead>
 <tbody>
   <% @users.each_with_index do |user,index| %>
   <tr>
     <td><%= index +1 %></td>
     <td><%= user.email %></td>
     <td><%= user.role %></td>
     <td><%= link_to 'Show', user %></td>
     <td><%= link_to "Edit", edit_user_path(user)%></td>
     <td><%= link_to "Destroy", user, method: :delete,
     data: { confirm: "Are you sure? "} %></td>
   </tr>
   <% end %>
 </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', root_path %>

app/views/users/reset_password.html.erb
<%= form_tag do %>
  <div>
    <%= hidden_field_tag :email, params[:email] %>
    <%= label_tag :password, 'Password:' %>
    <%= password_field_tag :password %>
  </div>

  <div>
    <%= label_tag :password_confirmation, 'Password_confirmation:' %>
    <%= password_field_tag :password_confirmation%>
  </div>

  <div>
    <%= submit_tag "Sumit" %> 
  </div>

<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
  <% if user_signed_in? %>
    <li><%= link_to "Log out", sessions_destroy_path, method: :delete %></li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to "Edit your profile", edit_user_path(current_user)%></li>
      </ul>
    </li>
    
    <% else %>
    <li><%= link_to "Log in", login_path %></li>
    <li><%= link_to "Sign up", new_user_path %></li>
  <%end %>